"""smb.conf rendering, reloads and Samba user management."""

from __future__ import annotations

import logging
import os
import posixpath
import pwd
import tempfile

from . import host
from .state import ACCESS_LEVELS, MEDIA_ROOT, State, is_under

_LOGGER = logging.getLogger(__name__)

SMB_CONF = os.environ.get("LS_SMB_CONF", "/etc/samba/smb.conf")
PASSDB = os.environ.get("LS_PASSDB", "/data/samba/passdb.tdb")
GUEST_ACCOUNT = "nobody"


def share_volume(share: dict, state: State) -> dict | None:
    """The configured volume a share's path lives on, if any."""
    for vol in state.volumes:
        if is_under(share["path"], posixpath.join(MEDIA_ROOT, vol["mount_name"])):
            return vol
    return None


def render(state: State, offline: set[str]) -> str:
    """Render smb.conf. Shares on volumes in `offline` (volume ids) are disabled
    so nothing is ever written into an empty mount folder on the system disk."""
    s = state.settings
    # Guest logins are only switched on while some share actually allows them.
    any_guest = any(sh.get("guest", "none") in ACCESS_LEVELS for sh in state.shares)
    lines = [
        "# Generated by the LUKS Disks & Samba add-on - changes will be overwritten.",
        "[global]",
        f"   workgroup = {s['workgroup']}",
        f"   server string = {s['server_string']}",
        "   server role = standalone server",
        "   security = user",
        f"   passdb backend = tdbsam:{PASSDB}",
        f"   map to guest = {'bad user' if any_guest else 'never'}",
        f"   guest account = {GUEST_ACCOUNT}",
        f"   restrict anonymous = {0 if any_guest else 2}",
        f"   server min protocol = {s['min_protocol']}",
        "   load printers = no",
        "   printing = bsd",
        "   printcap name = /dev/null",
        "   disable spoolss = yes",
        "   log level = 1",
        "   unix password sync = no",
    ]
    if s["hosts_allow"]:
        lines += [f"   hosts allow = {s['hosts_allow']}", "   hosts deny = ALL"]
    if s["macos"]:
        lines += [
            "   vfs objects = catia fruit streams_xattr",
            "   fruit:metadata = stream",
            "   fruit:model = MacSamba",
            "   fruit:posix_rename = yes",
            "   fruit:veto_appledouble = no",
            "   fruit:wipe_intentionally_left_blank_rfork = yes",
            "   fruit:delete_empty_adfiles = yes",
        ]

    for share in state.shares:
        access = {u: a for u, a in share.get("access", {}).items() if state.user(u)}
        vol = share_volume(share, state)
        guest = share.get("guest", "none")
        available = bool(access or guest in ACCESS_LEVELS) and not (vol and vol["id"] in offline)
        readers = sorted(u for u, a in access.items() if a == "ro")
        writers = sorted(u for u, a in access.items() if a == "rw")
        # Guest sessions run as GUEST_ACCOUNT, so it goes in the same lists.
        if guest == "ro":
            readers.append(GUEST_ACCOUNT)
        elif guest == "rw":
            writers.append(GUEST_ACCOUNT)
        lines += [
            "",
            f"[{share['name']}]",
            f"   path = {share['path']}",
            f"   comment = {share.get('comment', '')}",
            f"   browseable = {'yes' if share.get('browseable', True) else 'no'}",
            f"   available = {'yes' if available else 'no'}",
            f"   guest ok = {'yes' if guest in ACCESS_LEVELS else 'no'}",
            "   read only = yes",
            f"   valid users = {' '.join(readers + writers) or 'nobody'}",
            f"   write list = {' '.join(writers)}",
            # Access is controlled by the lists above; files are owned by root
            # like everything else under /media and /share.
            "   force user = root",
            "   force group = root",
            "   create mask = 0664",
            "   directory mask = 0775",
        ]
        if state.settings["veto_junk"]:
            lines += [
                "   veto files = /._*/.DS_Store/Thumbs.db/desktop.ini/",
                "   delete veto files = yes",
            ]
    return "\n".join(lines) + "\n"


def write_conf(state: State, offline: set[str]) -> None:
    os.makedirs(os.path.dirname(SMB_CONF), exist_ok=True)
    fd, tmp = tempfile.mkstemp(dir=os.path.dirname(SMB_CONF), prefix=".smb-")
    with os.fdopen(fd, "w", encoding="utf-8") as fh:
        fh.write(render(state, offline))
    os.chmod(tmp, 0o644)
    os.replace(tmp, SMB_CONF)


async def reload() -> None:
    res = await host.run("smbcontrol", "smbd", "reload-config", check=False)
    if res.rc != 0:
        _LOGGER.debug("smbd reload skipped: %s", res.err.strip() or res.out.strip())


async def close_share(name: str) -> None:
    await host.run("smbcontrol", "smbd", "close-share", name, check=False)


async def ensure_unix_user(name: str) -> None:
    try:
        pwd.getpwnam(name)
    except KeyError:
        await host.run("adduser", "-D", "-H", "-h", "/nonexistent", "-s", "/sbin/nologin",
                       "-g", "Samba user", name)


async def set_password(name: str, password: str) -> None:
    await ensure_unix_user(name)
    pw = password.encode()
    await host.run("smbpasswd", "-c", SMB_CONF, "-s", "-a", name, stdin=pw + b"\n" + pw + b"\n")
    await host.run("smbpasswd", "-c", SMB_CONF, "-e", name)


async def delete_user(name: str) -> None:
    await host.run("smbpasswd", "-c", SMB_CONF, "-x", name, check=False)
    await host.run("deluser", name, check=False)


async def passdb_users() -> set[str]:
    res = await host.run("pdbedit", "-s", SMB_CONF, "-L", check=False)
    return {line.split(":", 1)[0] for line in res.out.splitlines() if ":" in line}
